import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Shared/Layout/Layout";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Layout>
                    <h1 className="text-red-500 ">Landing Page</h1>
                </Layout>
            </main>
        </div>
    );
};

export default Home;
