import type { NextPage } from "next";
import Head from "next/head";
import HomePage from "../components/HomePage";
import ContentTool from "../components/HomePage/ContentTool";
import ConnectSales from './../components/HomePage/ConnectSales';
import OrganizedSeller from './../components/HomePage/OrganizedSeller';
import RapidRoute from './../components/HomePage/RapidRoute';
import DeliveryPersonalize from './../components/HomePage/DeliveryPersonalize';
import ContentDrop from './../components/HomePage/ContentDrop';
import CompanyLogo from './../components/HomePage/CompanyLogo';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      
      <HomePage />
      <ContentTool />
      <ConnectSales />
      <OrganizedSeller />
      <RapidRoute /> 
      <DeliveryPersonalize />
      <ContentDrop />
      <CompanyLogo />
    </div>
  );
};

export default Home;
